function obj = EBPlot(eb,field,input)
    label = [eb '.' field];
	if nargin < 3
        obj = MultiPlot({label, label},  {'activation', 'output'}, ...
            [1, 10], 'horizontal', {'YLim', [-15, 15], 'XGrid', 'on', 'YGrid', 'on'}, ...
            {{'b', 'LineWidth', 3}, {'r', 'LineWidth', 2}}, ...
            label, 'feature space', 'activation / output / input');
    else
        obj = MultiPlot({label, label, input}, {'activation', 'output', 'output'}, ...
            [1, 10, 1], 'horizontal', {'YLim', [-15, 15], 'XGrid', 'on', 'YGrid', 'on'}, ...
            {{'b', 'LineWidth', 3}, {'r', 'LineWidth', 2}, {'Color', [0, 0.75, 0], 'LineWidth', 2}}, ...
            label, 'feature space', 'activation / input / output');     
	end
    
end

